version: 0.2
phases:
  pre_build:
    commands:
      - npm run build
      - npm run build-auth-lambda
  build:
    commands:
      # Stack
      - aws cloudformation package --template-file ./deploy/main.yml --s3-bucket codepipelinehelloapi --s3-prefix artifacts/helloapi --output-template-file ./deploy/main.yml
artifacts:
  type: zip
  files:
    - ./**/*