AWSTemplateFormatVersion: "2010-09-09"
Description: Codepipeline stack for codepipeline-newapi
Parameters:
  GitHubOAuthToken:
    Type: String
    NoEcho: true
Resources:
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::749144762306:policy/codebuildpolicy

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: codepipeline-newapi 
      Description: Codepipeline stack for codepipeline-newapi
      ServiceRole: !GetAtt CodeBuildRole.Arn
      EncryptionKey: alias/codepipeline-kms-key
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:3.0
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      TimeoutInMinutes: 10
      Artifacts:
        Type: CODEPIPELINE

  CodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: codepipeline-newapi 
      RoleArn: arn:aws:iam::749144762306:role/Codepipelinerole
      ArtifactStore:
        Type: S3
        Location: codepipelinehelloapi
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              OutputArtifacts:
                - Name: GitHubSource
              Configuration:
                Owner: chisnallc
                Repo: HelloAPI
                Branch: main
                OAuthToken: !Ref GitHubOAuthToken # Maybe we dont need this because the repo is public
                PollForSourceChanges: false
              RunOrder: 1
        - Name: Build
          Actions:
          -
            ActionTypeId:
              Category: Build
              Owner: AWS
              Version: '1'
              Provider: CodeBuild
            InputArtifacts:
              - Name: GitHubSource
            OutputArtifacts:
              - Name: BuildStack
            RunOrder: 1
            Name: CodeBuild
            Configuration:
              ProjectName: !Ref 'CodeBuildProject'
        - Name: Deploy
          Actions:
            - Name: 'HelloApi-create-changeset'
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              InputArtifacts:
                - Name: BuildStack
              RunOrder: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: 'HelloApi-main-stack'
                ChangeSetName: 'HelloApi-changeset'
                RoleArn: 'arn:aws:iam::749144762306:role/codepipeline-execution-role'
                TemplatePath: BuildStack::deploy/main.yml
            - Name: HelloApi-runchangeset
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: '1'
                Provider: CloudFormation
              RunOrder: 2 
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                Capabilities: CAPABILITY_NAMED_IAM
                StackName: 'HelloApi-main-stack'
                ChangeSetName: 'HelloApi-changeset'
                RoleArn: 'arn:aws:iam::749144762306:role/codepipeline-execution-role'
