AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  MyRestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Description: Project API
      Name: HelloApiGateway
  MyRestApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:  
      HttpMethod: GET
      Integration: 
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: arn:aws:apigateway:region:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:749144762306:function:HelloApi/invocations
      ResourceID: !GetAtt MyRestApi.RootResourceId
      RestApiId: !Ref MyRestApi
    
      
     
